### PR TITLE
bug fix for issue #526 (Splitter loop gives different results in simulation and on FPGA board)

### LINKED ISSUE #526: Splitter loop gives different results in simulation and on FPGA board
A student found the following problem. The below circuit (cf. also to attached circuit file) yields different behaviour in simulation and after synthesis on an FPGA board:

grafik

In simulation, both LEDs will light up if the button is pressed. On the FPGA board, `LED_Bug` won't light up.

[VerteilerBug.zip](https://github.com/reds-heig/logisim-evolution/files/6164198/VerteilerBug.zip)

### PR DESCRIPTION
**Pull request by BFH-ktt1**
Fixes #526

### CODE REVIEW

**Comment by BFH-ktt1** [comment]
@MarcinOrlowski : Could you please review, such that I can merge?

File: src/main/java/com/cburch/logisim/fpga/designrulecheck/Netlist.java [hunk 1]
```diff
@@ -1740,49 +1745,51 @@ private SourceInfo GetHiddenSource(
...
       return true;
     }
     /* Check if we have a connection to another splitter */
-    for (Component currentSplitter : SplitterList) {
-      List<EndData> ends = currentSplitter.getEnds();
-      for (byte end = 0; end < ends.size(); end++) {
-        if (thisNet.contains(ends.get(end).getLocation())) {
+    for (var currentSplitter : splitterList) {
+      if (currentSplitter.equals(ignoreSplitter)) continue;
+      var ends = currentSplitter.getEnds();
```
Comment (MarcinOrlowski) [inline src/main/java/com/cburch/logisim/fpga/designrulecheck/Netlist.java:1782]: Unless I am mistaken, it can be `final`.

File: src/main/java/com/cburch/logisim/fpga/designrulecheck/Netlist.java [hunk 2]
```diff
@@ -1740,49 +1745,51 @@ private SourceInfo GetHiddenSource(
...
+      for (var end = 0; end < ends.size(); end++) {
+        if (combinedNet.contains(ends.get(end).getLocation())) {
           /* Here we have to process the inherited bits of the parent */
           byte[] BusBitConnection = ((Splitter) currentSplitter).GetEndpoints();
           if (end == 0) {
             /* this is a main net, find the connected end */
-            byte SplitterEnd = BusBitConnection[bitIndex];
+            byte SplitterEnd = BusBitConnection[combinedBitIndex];
```
Comment (MarcinOrlowski) [inline src/main/java/com/cburch/logisim/fpga/designrulecheck/Netlist.java:1789]: `final var`/`var` please.

File: src/main/java/com/cburch/logisim/fpga/designrulecheck/Netlist.java [hunk 3]
```diff
@@ -1740,49 +1745,51 @@ private SourceInfo GetHiddenSource(
...
             /* Find the corresponding Net index */
             Byte Netindex = 0;
-            for (int index = 0; index < bitIndex; index++) {
+            for (int index = 0; index < combinedBitIndex; index++) {
```
Comment (MarcinOrlowski) [inline src/main/java/com/cburch/logisim/fpga/designrulecheck/Netlist.java:1792]: `var` please for `index`

**Review by MarcinOrlowski — CHANGES_REQUESTED** [review]

File: src/main/java/com/cburch/logisim/file/XmlWriter.java [hunk 4]
```diff
@@ -157,7 +155,7 @@ static void sort(Node top) {
       final var a = new Node[n];
       for (int i = 0; i < n; i++) a[i] = children.item(i);
       Arrays.sort(a, nodeComparator);
-      for (int i = 0; i < n; i++) top.insertBefore(a[i], null); // moves a[i] to end
+//      for (int i = 0; i < n; i++) top.insertBefore(a[i], null); // moves a[i] to end
```
Comment (MarcinOrlowski) [inline src/main/java/com/cburch/logisim/file/XmlWriter.java]: Any reason for leaving commented out code? Please remove it or add a comment why it is commented out if you want to keep it.

**Review by MarcinOrlowski — CHANGES_REQUESTED** [review]

File: src/main/java/com/cburch/logisim/file/XmlWriter.java [hunk 5]
```diff
@@ -118,13 +118,13 @@ static int stringCompare(String a, String b) {
...
-        // worry about, since our normalization here is just for
-        // ease of comparing circ files during testing.
-        // System.out.printf("sorts equal:\n");
-        // System.out.printf(" a: <%s %s>%s\n", na, ma, va);
-        // System.out.printf(" b: <%s %s>%s\n", nb, mb, vb);
+    // This can happen in some cases, e.g. two text components
+    // on top of each other. But it seems rare enough to not
+    // worry about, since our normalization here is just for
+    // ease of comparing circ files during testing.
+    // System.out.printf("sorts equal:\n");
```
Comment (MarcinOrlowski) [inline src/main/java/com/cburch/logisim/file/XmlWriter.java:125]: Despite being commented out this is dead code when uncommented. If you want to keep it for any reason, please ensure `return c;` is the last statement of this method.

**Review by MarcinOrlowski — CHANGES_REQUESTED** [review]

File: src/main/java/com/cburch/logisim/file/XmlWriter.java (hunk 5 above)
Comment (BFH-ktt1) [reply src/main/java/com/cburch/logisim/file/XmlWriter.java:125]: Agree, will be fixed in the pinbug PR that I'm working on right now. Basically this file has nothing to do in this PR, I just don't know how to get it out :-) Any hints are welcomed

Comment (BFH-ktt1) [reply src/main/java/com/cburch/logisim/file/XmlWriter.java]: Okay, got it done, now the PR is clean

**Review by MarcinOrlowski — APPROVED** [review]
