### PR TITLE
Fix for fail to restart when vhdl code invalid

### LINKED ISSUE #1298: VHDL Simulator Restart
The "Restart VHDL simulator" command does not seem to be effective in the case errors are encountered in the vhdl code after a "VHDL Simulator Enabled". In this case to restart the simulation, Logisim must be closed and reopened. is this a bug?

### PR DESCRIPTION
**Pull request by esseivan**
closes #1298

### CODE REVIEW

**Comment by esseivan** [comment]
I wanted to fix only #1298 but I didn't knew that by uploading more to my develop branch once the pull request was made would change the PR as well

File: src/main/java/com/cburch/logisim/vhdl/sim/VhdlSimulatorTclBinder.java [hunk 1]
```diff
@@ -139,6 +142,9 @@ public void start() {
 
                 vsim.tclStartCallback();
                 return;
+              } else if (line.contains("\"vcom -reportprogress 300 -work work ../src/LogisimVhdlSimComp")) {
```
Comment (BFH-ktt1) [inline src/main/java/com/cburch/logisim/vhdl/sim/VhdlSimulatorTclBinder.java:145]: I do not like to much to check on a fixed String like this. I understand the idea, but is there not a better way to detect the end? Or if this is the only way, please add a final constant and make a remark in the code that this should always the last line.

**Review by BFH-ktt1 — CHANGES_REQUESTED** [review]

File: src/main/java/com/cburch/logisim/vhdl/sim/VhdlSimulatorTclBinder.java (hunk 1 above)
Comment (esseivan) [reply src/main/java/com/cburch/logisim/vhdl/sim/VhdlSimulatorTclBinder.java:145]: Basically (in my case) the error ends with : 

> \#     while executing
> \# "vcom -reportprogress 300 -work work ../src/LogisimVhdlSimComp_0.vhdl"

where the last line is the one generated at com/cburch/logisim/vhdl/sim/VhdlSimulatorTclComp.java:69 :

```
compFiles.append("vcom -reportprogress 300 -work work ../src/")
            .append(componentName)
            .append(".vhdl")
            .append(System.getProperty("line.separator"));
```

I don't know if there's an other way, but I could find a way to not use a fixed String

Comment (MarcinOrlowski) [reply src/main/java/com/cburch/logisim/vhdl/sim/VhdlSimulatorTclBinder.java:145]: I second @BFH-ktt1 - hardcoded strings are asking for trobules. But I think that we can meet in the middle here because

    "vcom -reportprogress 300 -work work ../src/LogisimVhdlSimComp_0.vhdl"

is built by code:

```
compFiles.append("vcom -reportprogress 300 -work work ../src/") .append(componentName)
            .append(".vhdl")
            ...
```

you should build the string you match against:

    else if (line.contains("\"vcom -reportprogress 300 -work work ../src/LogisimVhdlSimComp"))

the same way which would prevent problems when if any case we decide `componentName` to be differently built.
```

**Review by MarcinOrlowski — CHANGES_REQUESTED** [review]

File: src/main/java/com/cburch/logisim/vhdl/sim/VhdlSimulatorTclBinder.java [hunk 2]
```diff
@@ -105,6 +105,8 @@ public void start() {
             // FIXME: hardcoded string
             final var errorMessage = new StringBuilder(
                     "You may disable VHDL simulation in the simulation menu if this occurs again\n\n");
+            
+            String msgCheckOnError = "\"" + VhdlSimConstants.VHDL_COMPILE_COMMAND + VhdlSimConstants.VHDL_COMPONENT_SIM_NAME;
```
Comment (BFH-ktt1) [inline src/main/java/com/cburch/logisim/vhdl/sim/VhdlSimulatorTclBinder.java:109]: Please avoid "+" in string concatinations, Please use `String.format("\"%s%s",VhdlSimConstants.VHDL_COMPILE_COMMAND, VhdlSimConstants.VHDL_COMPONENT_SIM_NAME);` instead

Comment (esseivan) [reply src/main/java/com/cburch/logisim/vhdl/sim/VhdlSimulatorTclBinder.java]: Done in the most recent commit

**Review by BFH-ktt1 — APPROVED** [review]

File: src/main/java/com/cburch/logisim/vhdl/base/VhdlSimConstants.java [hunk 3]
```diff
@@ -77,6 +77,8 @@ public boolean isHidden() {
   public static final String SIM_COMP_PATH = SIM_PATH + "comp/";
   public static final String SIM_TOP_FILENAME = "top_sim.vhdl";
   public static final String VHDL_COMPONENT_SIM_NAME = "LogisimVhdlSimComp_";
+  // FIXME: hardcoded path. The "../src/" asks for troubles!
+  public static final String VHDL_COMPILE_COMMAND = "vcom -reportprogress 300 -work work ../src/";
```
Comment (maehne) [inline src/main/java/com/cburch/logisim/vhdl/base/VhdlSimConstants.java:81]: Fine with me for the moment. Did you check that this works on Windows, too? I know that inside the Tcl shell paths with slash and backslash work in princible (if properly escaped).

**Review by maehne — APPROVED** [review]

File: src/main/java/com/cburch/logisim/vhdl/base/VhdlSimConstants.java (hunk 3 above)
Comment (esseivan) [reply src/main/java/com/cburch/logisim/vhdl/base/VhdlSimConstants.java:81]: I just moved to the constants class, I'm not the author of this command. But I'm on Windows and had no issue with it

File: src/main/java/com/cburch/logisim/vhdl/sim/VhdlSimulatorTclBinder.java (hunk 1 above)
Comment (maehne) [reply src/main/java/com/cburch/logisim/vhdl/sim/VhdlSimulatorTclBinder.java]: @esseivan: This comment by @MarcinOrlowski still needs to be addressed before merging -- unless he is fine with your proposal in the meantime.

**Comment by esseivan** [comment]
Just to be sure, is there something else I need to fix here ?

**Comment by maehne** [comment]
@esseivan: Merging is still blocked due to the change requested by @MarcinOrlowski.

@MarcinOrlowski: Do you insist on this change? Or can we merge it anyway? Otherwise, could you maybe assist @esseivan to implement it?

**Comment by esseivan** [comment]
> @esseivan: Merging is still blocked due to the change requested by @MarcinOrlowski.

I changed what was requested, didn't I ?

File: src/main/java/com/cburch/logisim/vhdl/sim/VhdlSimulatorTclBinder.java [hunk 4]
```diff
@@ -105,6 +105,9 @@ public void start() {
             // FIXME: hardcoded string
             final var errorMessage = new StringBuilder(
                     "You may disable VHDL simulation in the simulation menu if this occurs again\n\n");
+            
+            String msgCheckOnError = String.format("\"%s%s",
```
Comment (MarcinOrlowski) [inline src/main/java/com/cburch/logisim/vhdl/sim/VhdlSimulatorTclBinder.java:109]: `final var` instead of `String` please.

**Review by MarcinOrlowski — DISMISSED** [review]

**Comment by MarcinOrlowski** [comment]
@esseivan yep, we almost there. Just one more minor change please.

File: src/main/java/com/cburch/logisim/vhdl/sim/VhdlSimulatorTclBinder.java (hunk 4 above)
Comment (MarcinOrlowski) [reply src/main/java/com/cburch/logisim/vhdl/sim/VhdlSimulatorTclBinder.java:109]: Also, why isn't second "%s" (and also opening `\"` - I assume it's intentionally not closed) part of `VHDL_COMPILE_COMMAND`?

Comment (esseivan) [reply src/main/java/com/cburch/logisim/vhdl/sim/VhdlSimulatorTclBinder.java:109]: `VHDL_COMPILE_COMMAND` is also used by
```
compFiles.append(VhdlSimConstants.VHDL_COMPILE_COMMAND)
            .append(componentName)
            .append(".vhdl")
            .append(System.getProperty("line.separator"));
```
So I didn't changed the function, I just replaced the string with the constant.
I could include the "%s" in the constant but then the said line should also be changed.
And yes, the not closed `\"` is intentional

Comment (MarcinOrlowski) [reply src/main/java/com/cburch/logisim/vhdl/sim/VhdlSimulatorTclBinder.java]: OK, thanks for clarification.

**Review by maehne — APPROVED** [review]
Thanks @esseivan for addressing the remarks by @MarcinOrlowski! Looks good to me!
