### PR TITLE
Fix TTL 7436 pin arrangement

### LINKED ISSUE #1474: TTL 7436 has incorrect pin placement
7436 ICs differ from 7402 in their pin arrangement, so just extending the 7402 class is incorrect.

### PR DESCRIPTION
**Pull request by btb**
fixes #1474

### CODE REVIEW

File: src/main/java/com/cburch/logisim/std/ttl/Ttl7436.java [hunk 1]
```diff
@@ -18,7 +25,46 @@ public class Ttl7436 extends Ttl7402 {
    */
   public static final String _ID = "7436";
 
+  private static class NorGateHdlGeneratorFactory extends AbstractGateHdlGenerator {
+    @Override
+    public LineBuffer getLogicFunction(int index) {
+      return LineBuffer.getHdlBuffer()
+          .add("{{assign}}gateO{{1}}{{=}}{{not}}(gateA{{1}}{{or}}gateB{{1}});", index);
```
Comment (BFH-ktt1) [inline src/main/java/com/cburch/logisim/std/ttl/Ttl7436.java:32]: why not ```{{=}} gateA{{1}} {{nor}} gateB{{1}}``` ?

Comment (btb) [reply src/main/java/com/cburch/logisim/std/ttl/Ttl7436.java:32]: this is just a copy of the code in Ttl7402, so maybe cleaning that up should be a separate issue

**Review by BFH-ktt1 — APPROVED** [review]
