### PR TITLE
fixed dotmatrix -> LED array mapping and a null-pointer exception (fixes #878)

### LINKED ISSUE #878: dotmatrix mapps incorrectly to LED-Array
When mapping a dot-matrix to the LED-Array (currently checked for input-format colums) will invert the rows on the LED-Array

### PR DESCRIPTION
**Pull request by BFH-ktt1**

### CODE REVIEW

File: src/main/java/com/cburch/logisim/std/io/DotMatrixHDLGeneratorFactory.java [hunk 1]
```diff
@@ -57,32 +57,60 @@
...
+        final var ledMatrixRow = rows - dotMatrixRow - 1;
+        for (var ledMatrixCol = 0; ledMatrixCol < cols; ledMatrixCol++) {
           final var rowWire = (rows == 1) ? GetNetName(componentInfo, 1, true, netlist)
-              : GetBusEntryName(componentInfo, 1, true, thisRow, netlist);
+              : GetBusEntryName(componentInfo, 1, true, dotMatrixRow, netlist);
           final var colWire = (cols == 1) ? GetNetName(componentInfo, 0, true, netlist)
-              : GetBusEntryName(componentInfo, 0, true, thisCol, netlist);
-          final var idx = thisRow * cols + thisCol + componentInfo.GetLocalBubbleOutputStartId();
+              : GetBusEntryName(componentInfo, 0, true, ledMatrixCol, netlist);
+          final var idx = ledMatrixRow * cols + ledMatrixCol + componentInfo.GetLocalBubbleOutputStartId();
```
Comment (MarcinOrlowski) [inline src/main/java/com/cburch/logisim/std/io/DotMatrixHDLGeneratorFactory.java:113]: Please wrap multiplication in brackets.

File: src/main/java/com/cburch/logisim/std/io/DotMatrixHDLGeneratorFactory.java [hunk 2]
```diff
@@ -57,32 +57,60 @@
...
+       *  hence the cols are inverted to the definition of the LED-Matrix that uses:
+       *  r0,c0 r0,c1
+       *  r1,c0 r1,c1
+       */
+      for (var ledMatrixRow = 0; ledMatrixRow < rows; ledMatrixRow++) {
+        for (var dotMatrixCol = 0; dotMatrixCol < cols; dotMatrixCol++) {
+          final var ledMatrixCol = cols - dotMatrixCol - 1;
+          final var wire = (cols == 1) ? GetNetName(componentInfo, ledMatrixRow, true, netlist)
+              : GetBusEntryName(componentInfo, ledMatrixRow, true, ledMatrixCol, netlist);
+          final var idx = ledMatrixRow * cols + dotMatrixCol + componentInfo.GetLocalBubbleOutputStartId();
```
Comment (MarcinOrlowski) [inline src/main/java/com/cburch/logisim/std/io/DotMatrixHDLGeneratorFactory.java:92]: Please wrap multiplication in brackets.

File: src/main/java/com/cburch/logisim/std/io/DotMatrixHDLGeneratorFactory.java [hunk 3]
```diff
@@ -57,32 +57,60 @@
...
+       *  hence the rows are inverted to the definition of the LED-Matrix that uses:
+       *  r0,c0 r0,c1
+       *  r1,c0 r1,c1
+       */
+      for (var dotMatrixRow = 0; dotMatrixRow < rows; dotMatrixRow++) {
+        final var ledMatrixRow = rows - dotMatrixRow - 1;
+        for (var ledMatrixCol = 0; ledMatrixCol < cols; ledMatrixCol++) {
+          final var wire = (rows == 1) ? GetNetName(componentInfo, ledMatrixCol, true, netlist) 
+              : GetBusEntryName(componentInfo, ledMatrixCol, true, dotMatrixRow, netlist);
+          final var idx = ledMatrixRow * cols + ledMatrixCol + componentInfo.GetLocalBubbleOutputStartId();
```
Comment (MarcinOrlowski) [inline src/main/java/com/cburch/logisim/std/io/DotMatrixHDLGeneratorFactory.java:73]: Please wrap multiplication in brackets.

File: src/main/java/com/cburch/logisim/std/io/DotMatrixHDLGeneratorFactory.java [hunk 4]
```diff
@@ -57,32 +57,60 @@
...
+       *  r0,c0 r0,c1
+       *  
+       *  hence the rows are inverted to the definition of the LED-Matrix that uses:
+       *  r0,c0 r0,c1
+       *  r1,c0 r1,c1
+       */
+      for (var dotMatrixRow = 0; dotMatrixRow < rows; dotMatrixRow++) {
+        final var ledMatrixRow = rows - dotMatrixRow - 1;
+        for (var ledMatrixCol = 0; ledMatrixCol < cols; ledMatrixCol++) {
+          final var wire = (rows == 1) ? GetNetName(componentInfo, ledMatrixCol, true, netlist)
```
Comment (MarcinOrlowski) [inline src/main/java/com/cburch/logisim/std/io/DotMatrixHDLGeneratorFactory.java:71]: These looped ternariy assignments look pretty similar here in 3 loop blocks. Any chance to extract this code to separate method and reduce overall LoC?

**Review by MarcinOrlowski — CHANGES_REQUESTED** [review]

File: src/main/java/com/cburch/logisim/std/io/DotMatrixHDLGeneratorFactory.java (hunk 4 above)
Comment (BFH-ktt1) [reply src/main/java/com/cburch/logisim/std/io/DotMatrixHDLGeneratorFactory.java:71]: As the code is already the minimal, I could think of making an other loop and do the switch inside the loop, but I am not sure this would improve readability. For the moment I think the code is as condense at it can be, adding another file for this will not resolve the nr. of code lines. So I prefer that it stays this way.

**Review by MarcinOrlowski — APPROVED** [review]
